baseURL = "https://blog.thomasruiz.fr/"
languageCode = "en-us"
title = "Thomas Ruiz Blog"
theme = "ananke"

[params]
  dateFormat = "02 January 2006"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/pages/intro"

