baseURL = "https://blog.thomasruiz.fr/"
languageCode = "en-us"
title = "Thomas Ruiz Blog"
theme = "hugo-paper"

googleAnalytics = "UA-83359557-1"

[params]
  dateFormat = "02 January 2006"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/pages/about-me"

